url: https://mvassaux.github.io
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude: ["CNAME", "README.md", "Gemfile", "Gemfile.lock"]
include: []
gems:
  - jekyll-sitemap
  - jemoji
