url: https://mvassaux.github.io
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude: ["vendor", "CNAME", "README.md", "Gemfile", "Gemfile.lock"]
include: []
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-twitter-plugin
